# -*- coding: utf-8 -*-
"""666.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Nu467sJ535pk-KIE4kUpTG4vTCJPzGQN
"""

import streamlit as st
import pandas as pd
import joblib

# Load model and encoders
model = joblib.load("modell (1).pkl")
encoders = joblib.load("encoders (1).pkl")

st.title("🚗 Car Condition Prediction")

# User inputs (matching training features)
brand = st.selectbox("Brand", encoders['Brand'].classes_)
model_name = st.selectbox("Model", encoders['Model'].classes_)
fuel = st.selectbox("Fuel Type", encoders['FuelType'].classes_)
region = st.selectbox("Region", encoders['Region'].classes_)
transmission = st.selectbox("Transmission", encoders['Transmission'].classes_)
color = st.selectbox("Color", encoders['Color'].classes_)
type_ = st.selectbox("Type", encoders['Type'].classes_)

driven_km = st.number_input("Driven KM", min_value=0)
enginev = st.number_input("Engine Volume (L)", min_value=0.0, format="%.1f")

# Encode inputs
input_dict = {
    'Brand': encoders['Brand'].transform([brand])[0],
    'Model': encoders['Model'].transform([model_name])[0],
    'FuelType': encoders['FuelType'].transform([fuel])[0],
    'Region': encoders['Region'].transform([region])[0],
    'Transmission': encoders['Transmission'].transform([transmission])[0],
    'Color': encoders['Color'].transform([color])[0],
    'Type': encoders['Type'].transform([type_])[0],
    'Driven_KM': driven_km,
    'EngineV': enginev
}

input_df = pd.DataFrame([input_dict])

# Predict
if st.button("Predict Condition"):
    pred = model.predict(input_df)[0]
    condition_label = encoders['Condition'].inverse_transform([pred])[0]
    st.success(f"🧠 The predicted condition is: **{condition_label}**")